version: "3.9"

services:
  projects:
    build:
      context: ./ProjectsMicroservice
      dockerfile: Dockerfile
    container_name: projects_microservice
    ports:
      - "8001:8000"
    env_file:
      - ./ProjectsMicroservice/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./ProjectsMicroservice
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: ./ProjectsMicroservice/requirements.txt

  issues:
    build:
      context: ./IssuesMicroservice
      dockerfile: Dockerfile
    container_name: issues_microservice
    ports:
      - "8002:8000"
    env_file:
      - ./IssuesMicroservice/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./IssuesMicroservice
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: ./IssuesMicroservice/requirements.txt

  comments:
    build:
      context: ./CommentsMicroservice
      dockerfile: Dockerfile
    container_name: comments_microservice
    ports:
      - "8003:8000"
    env_file:
      - ./CommentsMicroservice/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./CommentsMicroservice
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: ./CommentsMicroservice/requirements.txt
